name: module_login
description: A new Flutter package project.
version: 0.0.1
author: Toshi Ossada
homepage: https://www.ioasys.com.br/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  commons:
    path: "../commons"
  commons_dependencies:
    path: "../commons_dependencies"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_modular_test: ^1.0.1
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.2.1
  mockito: ^5.0.5
  triple_test: ^0.0.5
  effective_dart: ^1.3.1
